import Head from 'next/head'
import { useMemo, useState } from 'react'
import useDebounce from 'react-use/lib/useDebounce'

type RawTxn = {
  date: string
  currency: string
  amount: string
  balance: string
  description: string
  raw: string
}

const txnReg = new RegExp(/^\d{4}-\d{2}-\d{2} CNY [-0-9.,]+ [-0-9.,]+ .*$/)

export default function Home() {
  const [rawText, setRawText] = useState('')
  const [debouncedText, setDebouncedText] = useState('')
  useDebounce(() => { setDebouncedText(rawText) }, 200, [rawText])

  const [accountName, setAccountName] = useState('')

  const parsedLines = useMemo(() => {
    const result = [] as string[]
    let line = "";
    const lines = debouncedText.split('\n')
    for (const [index, item] of lines.entries()) {
      const match = txnReg.test(item)
      if (match) {
        if (line) {
          result.push(line)
        }
        line = item
      } else {
        line += item
      }
      if (index === lines.length - 1) {
        if (line) {
          result.push(line)
        }
      }
    }
    return result
  }, [debouncedText])

  const parsedTxns = useMemo(() => {
    const result = [] as RawTxn[]
    for (const line of parsedLines) {
      const [date, currency, amount, balance, ...description] = line.split(' ')
      result.push({
        date,
        currency,
        amount,
        balance,
        description: description.join(' '),
        raw: line
      })
    }
    return result
  }, [parsedLines])

  const renderedBeancounts = useMemo(() => {
    const result = [] as string[]

    for (const txn of parsedTxns) {
      const { date, currency, amount, balance, description } = txn
      result.push(`; ${txn.raw}`)
      result.push(`${date} ! "${description}"`)
      result.push(`  ${accountName} ${amount} ${currency}`)
      result.push(`  Expenses:Unknown`)
      result.push('')
    }

    return result
  }, [parsedTxns, accountName])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container flex h-screen bg-gray-200 mx-auto'>
        <div className='w-1/2'>
          <div className='w-full h-1/2 p-4'>
            <textarea className='textarea w-full h-full'
              value={rawText}
              onChange={(e) => setRawText(e.target.value)}
            ></textarea>
          </div>
          <div className='w-full h-1/2 p-4'>
            <p>Rules:</p>
            <div className='cards w-full'>
              <div className="card bg-slate-50">
                <div className='card-body'>
                  <h2 className='card-title'>如果字段 raw 中包含 包笼天下 </h2>
                  <p>设置 Payee 为 包笼天下</p>
                  <p>设置 Narration 为 早饭</p>
                  <p>设置收款账户为 Expenses:CN:生活:饮食:堂食</p>
                  <p>标记交易为 完成</p>
                </div>
              </div>
            </div>

          </div>
        </div>
        <div className='w-1/2 p-4 flex flex-col'>
          <div className='py-2'>
            <input type="text" className='input w-full flex-none'
              value={accountName}
              onChange={(e) => setAccountName(e.target.value)}
              placeholder='<Your-Account-Name>'
            ></input>
          </div>
          <textarea className='textarea w-full flex-1'
            readOnly
            value={renderedBeancounts.join('\n')}
          ></textarea>
        </div>
      </main>
    </div>
  )
}
