import Head from 'next/head'
import { useMemo, useState } from 'react'
import useDebounce from 'react-use/lib/useDebounce'

type Txn = {
  date: string
  currency: string
  amount: string
  balance: string
  description: string
  raw: string
}

const txnReg = new RegExp(/^\d{4}-\d{2}-\d{2} CNY [-0-9.,]+ [-0-9.,]+ .*$/)

export default function Home() {
  const [rawText, setRawText] = useState('')
  const [debouncedText, setDebouncedText] = useState('')
  useDebounce(() => { setDebouncedText(rawText) }, 200, [rawText])

  const [accountName, setAccountName] = useState('')

  const parsedLines = useMemo(() => {
    const result = [] as string[]
    let line = "";
    const lines = debouncedText.split('\n')
    for (const [index, item] of lines.entries()) {
      const match = txnReg.test(item)
      if (match) {
        if (line) {
          result.push(line)
        }
        line = item
      } else {
        line += item
      }
      if (index === lines.length - 1) {
        if (line) {
          result.push(line)
        }
      }
    }
    return result
  }, [debouncedText])

  const parsedTxns = useMemo(() => {
    const result = [] as Txn[]
    for (const line of parsedLines) {
      const [date, currency, amount, balance, ...description] = line.split(' ')
      result.push({
        date,
        currency,
        amount,
        balance,
        description: description.join(' '),
        raw: line
      })
    }
    return result
  }, [parsedLines])

  const renderedBeancounts = useMemo(() => {
    const result = [] as string[]

    for (const txn of parsedTxns) {
      const { date, currency, amount, balance, description } = txn
      result.push(`; ${txn.raw}`)
      result.push(`${date} ! "${description}"`)
      result.push(`  ${accountName} ${amount} ${currency}`)
      result.push(`  Expenses:Unknown`)
      result.push('')
    }

    return result
  }, [parsedTxns, accountName])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container flex h-screen bg-neutral-200 mx-auto'>
        <div className='w-1/2 p-4'>
          <textarea className='w-full h-1/3'
            value={rawText}
            onChange={(e) => setRawText(e.target.value)}
          ></textarea>
          <textarea className='w-full h-1/3'
            readOnly
            value={parsedLines.join('\n')}>
          </textarea>
          <textarea className='w-full h-1/3'
            readOnly
            value={JSON.stringify(parsedTxns)}>
          </textarea>
        </div>
        <div className='w-1/2 p-4'>
          <div className='py-2'>
            <input type="text" className='w-full'
            value={accountName}
            onChange={(e) => setAccountName(e.target.value)}
            placeholder='<Your-Account-Name>'
            ></input>
          </div>
          <textarea className='w-full h-full'
            readOnly
            value={renderedBeancounts.join('\n')}
          ></textarea>
        </div>
      </main>
    </div>
  )
}
